import java.util.*;

/**
 * Auto-generated dispatcher for: ScalifiedWrapper
 * Generated by DispatcherGenerator
 * DO NOT EDIT - Regenerate if the source class changes
 */
public class GeneratedDispatcher implements GenericContractsTest.Dispatcher {

    public String getClassName() {
        return "ScalifiedWrapper";
    }

    public Object createInstance() {
        return new ScalifiedWrapper();
    }

    public void executeStateInit(Object instance, int stateVar) {
        ScalifiedWrapper obj = (ScalifiedWrapper) instance;
        if (stateVar >= 1) obj.add(1);
        if (stateVar >= 2) obj.add(2);
        if (stateVar >= 3) obj.add(3);
    }

    public Object executeMethod(Object instance, String methodName, String[] args, Map<String, Integer> symVars) {
        ScalifiedWrapper obj = (ScalifiedWrapper) instance;
        Integer arg1 = (args.length > 0) ? resolveArg(args[0], symVars) : null;
        Integer arg2 = (args.length > 1) ? resolveArg(args[1], symVars) : null;
        Integer arg3 = (args.length > 2) ? resolveArg(args[2], symVars) : null;

        if (methodName.equals("isLeaf")) {
            return obj.isLeaf();
        } else if (methodName.equals("add")) {
            obj.add(arg1);
            return null;
        } else if (methodName.equals("remove")) {
            return obj.remove(arg1);
        } else if (methodName.equals("isEmpty")) {
            return obj.isEmpty();
        } else if (methodName.equals("contains")) {
            return obj.contains(arg1);
        } else if (methodName.equals("size")) {
            return obj.size();
        }
        return null;
    }

    public boolean evaluatePredicate(Object instance, String pred, Map<String, Integer> symVars) {
        ScalifiedWrapper obj = (ScalifiedWrapper) instance;

        if (pred.equals("isLeaf") || pred.equals("isLeaf()"))
            return obj.isLeaf();
        if (pred.equals("isEmpty") || pred.equals("isEmpty()"))
            return obj.isEmpty();

        if (pred.startsWith("contains(") && pred.endsWith(")")) {
            String varName = pred.substring(9, pred.length() - 1).trim();
            Integer value = resolveArg(varName, symVars);
            return value != null && obj.contains(value);
        }

        return false;
    }

    public int getSize(Object instance) {
        ScalifiedWrapper obj = (ScalifiedWrapper) instance;
        return obj.size();
    }

    private Integer resolveArg(String arg, Map<String, Integer> symVars) {
        if (symVars.containsKey(arg)) {
            return symVars.get(arg);
        }
        try {
            return Integer.parseInt(arg);
        } catch (NumberFormatException e) {
            return null;
        }
    }
}
