import java.lang.reflect.*;
import java.io.*;
import java.util.*;

public class DispatcherGenerator {

    public static void main(String[] args) {
        if (args.length < 1) {
            System.out.println("Usage: java DispatcherGenerator <ClassName> [outputFile]");
            System.out.println("Example: java DispatcherGenerator BoundedList");
            return;
        }

        String className = args[0];
        String outputFile = args.length > 1 ? args[1] : "GeneratedDispatcher.java";

        try {
            Class<?> clazz = Class.forName(className);
            String code = generateDispatcher(clazz);
            
            PrintWriter writer = new PrintWriter(new FileWriter(outputFile));
            writer.print(code);
            writer.close();
            
            System.out.println("[+] Generated dispatcher for: " + className);
            System.out.println("[+] Output written to: " + outputFile);
            System.out.println("\n[*] Next steps:");
            System.out.println("    1. Compile: javac " + outputFile + " " + className + ".java GenericContractsTest.java");
            System.out.println("    2. Run JPF: java -jar jpf-core/build/RunJPF.jar generic_verify.jpf");
            
        } catch (ClassNotFoundException e) {
            System.err.println("[ERROR] Class not found: " + className);
            System.err.println("        Make sure the class is compiled and in classpath.");
        } catch (IOException e) {
            System.err.println("[ERROR] Could not write output file: " + e.getMessage());
        }
    }

    private static String generateDispatcher(Class<?> clazz) {
        StringBuilder sb = new StringBuilder();
        String className = clazz.getSimpleName();

        // Header
        sb.append("import java.util.*;\n\n");
        sb.append("/**\n");
        sb.append(" * Auto-generated dispatcher for: " + className + "\n");
        sb.append(" * Generated by DispatcherGenerator\n");
        sb.append(" * DO NOT EDIT - Regenerate if the source class changes\n");
        sb.append(" */\n");
        sb.append("public class GeneratedDispatcher implements GenericContractsTest.Dispatcher {\n\n");

        // getClassName
        sb.append("    public String getClassName() {\n");
        sb.append("        return \"" + className + "\";\n");
        sb.append("    }\n\n");

        // createInstance
        sb.append("    public Object createInstance() {\n");
        sb.append("        return new " + className + "();\n");
        sb.append("    }\n\n");

        // Analyze methods
        Method[] methods = clazz.getDeclaredMethods();
        List<Method> publicMethods = new ArrayList<Method>();
        Method sizeMethod = null;
        List<Method> booleanPredicates = new ArrayList<Method>();
        List<Method> voidMethods = new ArrayList<Method>();
        List<Method> returningMethods = new ArrayList<Method>();

        for (Method m : methods) {
            if (Modifier.isPublic(m.getModifiers())) {
                publicMethods.add(m);
                
                String name = m.getName();
                Class<?> returnType = m.getReturnType();
                Class<?>[] params = m.getParameterTypes();

                if (name.equals("size") && params.length == 0) {
                    sizeMethod = m;
                } else if (returnType == boolean.class && params.length == 0) {
                    booleanPredicates.add(m);
                } else if (returnType == void.class) {
                    voidMethods.add(m);
                } else {
                    returningMethods.add(m);
                }
            }
        }

        // Generate executeStateInit - look for common add methods
        sb.append("    public void executeStateInit(Object instance, int stateVar) {\n");
        sb.append("        " + className + " obj = (" + className + ") instance;\n");
        
        // Find an "add" method (push, add, enqueue, insert, etc.)
        Method addMethod = findAddMethod(publicMethods);
        if (addMethod != null) {
            sb.append("        if (stateVar >= 1) obj." + addMethod.getName() + "(");
            sb.append(getDefaultArgs(addMethod, "1"));
            sb.append(");\n");
            sb.append("        if (stateVar >= 2) obj." + addMethod.getName() + "(");
            sb.append(getDefaultArgs(addMethod, "2"));
            sb.append(");\n");
            sb.append("        if (stateVar >= 3) obj." + addMethod.getName() + "(");
            sb.append(getDefaultArgs(addMethod, "3"));
            sb.append(");\n");
        } else {
            sb.append("        // No suitable add method found - customize manually\n");
        }
        sb.append("    }\n\n");

        // Generate executeMethod
        sb.append("    public Object executeMethod(Object instance, String methodName, String[] args, Map<String, Integer> symVars) {\n");
        sb.append("        " + className + " obj = (" + className + ") instance;\n");
        sb.append("        Integer arg1 = (args.length > 0) ? resolveArg(args[0], symVars) : null;\n");
        sb.append("        Integer arg2 = (args.length > 1) ? resolveArg(args[1], symVars) : null;\n");
        sb.append("        Integer arg3 = (args.length > 2) ? resolveArg(args[2], symVars) : null;\n\n");

        boolean first = true;
        for (Method m : publicMethods) {
            String name = m.getName();
            Class<?>[] params = m.getParameterTypes();
            Class<?> returnType = m.getReturnType();

            // Skip getClass, toString, etc.
            if (name.equals("getClass") || name.equals("toString") || 
                name.equals("hashCode") || name.equals("equals") ||
                name.equals("notify") || name.equals("notifyAll") || name.equals("wait")) {
                continue;
            }

            sb.append("        ");
            if (!first) sb.append("} else ");
            first = false;
            
            sb.append("if (methodName.equals(\"" + name + "\")) {\n");
            sb.append("            ");
            
            if (returnType != void.class) {
                sb.append("return ");
            }
            
            sb.append("obj." + name + "(");
            sb.append(generateArgList(params));
            sb.append(");\n");
            
            if (returnType == void.class) {
                sb.append("            return null;\n");
            }
        }
        
        if (!first) {
            sb.append("        }\n");
        }
        sb.append("        return null;\n");
        sb.append("    }\n\n");

        // Generate evaluatePredicate
        sb.append("    public boolean evaluatePredicate(Object instance, String pred, Map<String, Integer> symVars) {\n");
        sb.append("        " + className + " obj = (" + className + ") instance;\n\n");

        // Boolean predicates (no args)
        for (Method m : booleanPredicates) {
            String name = m.getName();
            sb.append("        if (pred.equals(\"" + name + "\") || pred.equals(\"" + name + "()\"))\n");
            sb.append("            return obj." + name + "();\n");
        }
        sb.append("\n");

        // contains-style methods (boolean with one arg)
        for (Method m : publicMethods) {
            if (m.getReturnType() == boolean.class && m.getParameterCount() == 1) {
                String name = m.getName();
                Class<?> paramType = m.getParameterTypes()[0];
                
                sb.append("        if (pred.startsWith(\"" + name + "(\") && pred.endsWith(\")\")) {\n");
                sb.append("            String varName = pred.substring(" + (name.length() + 1) + ", pred.length() - 1).trim();\n");
                sb.append("            Integer value = resolveArg(varName, symVars);\n");
                
                if (paramType == Integer.class || paramType == int.class) {
                    sb.append("            return value != null && obj." + name + "(value);\n");
                } else {
                    sb.append("            return value != null && obj." + name + "(value);\n");
                }
                sb.append("        }\n");
            }
        }

        sb.append("\n        return false;\n");
        sb.append("    }\n\n");

        // Generate getSize
        sb.append("    public int getSize(Object instance) {\n");
        sb.append("        " + className + " obj = (" + className + ") instance;\n");
        if (sizeMethod != null) {
            sb.append("        return obj.size();\n");
        } else {
            sb.append("        return 0; // No size() method found\n");
        }
        sb.append("    }\n\n");

        // Generate resolveArg helper
        sb.append("    private Integer resolveArg(String arg, Map<String, Integer> symVars) {\n");
        sb.append("        if (symVars.containsKey(arg)) {\n");
        sb.append("            return symVars.get(arg);\n");
        sb.append("        }\n");
        sb.append("        try {\n");
        sb.append("            return Integer.parseInt(arg);\n");
        sb.append("        } catch (NumberFormatException e) {\n");
        sb.append("            return null;\n");
        sb.append("        }\n");
        sb.append("    }\n");

        sb.append("}\n");

        return sb.toString();
    }

    private static Method findAddMethod(List<Method> methods) {
        String[] addMethodNames = {"push", "add", "enqueue", "insert", "put", "offer"};
        
        for (String name : addMethodNames) {
            for (Method m : methods) {
                if (m.getName().equals(name) && m.getParameterCount() >= 1) {
                    return m;
                }
            }
        }
        return null;
    }

    private static String getDefaultArgs(Method m, String value) {
        Class<?>[] params = m.getParameterTypes();
        StringBuilder sb = new StringBuilder();
        
        for (int i = 0; i < params.length; i++) {
            if (i > 0) sb.append(", ");
            
            Class<?> p = params[i];
            if (p == int.class || p == Integer.class) {
                sb.append(value);
            } else if (p == String.class) {
                sb.append("\"" + value + "\"");
            } else if (p == boolean.class || p == Boolean.class) {
                sb.append("true");
            } else if (p == double.class || p == Double.class) {
                sb.append(value + ".0");
            } else {
                sb.append("null");
            }
        }
        return sb.toString();
    }

    private static String generateArgList(Class<?>[] params) {
        StringBuilder sb = new StringBuilder();
        
        for (int i = 0; i < params.length; i++) {
            if (i > 0) sb.append(", ");
            
            String argName = "arg" + (i + 1);
            Class<?> p = params[i];
            
            if (p == int.class) {
                sb.append(argName + " != null ? " + argName + ".intValue() : 0");
            } else if (p == Integer.class) {
                sb.append(argName);
            } else if (p == String.class) {
                sb.append(argName + " != null ? " + argName + ".toString() : null");
            } else if (p == boolean.class) {
                sb.append(argName + " != null && " + argName + " != 0");
            } else if (p == double.class) {
                sb.append(argName + " != null ? " + argName + ".doubleValue() : 0.0");
            } else {
                sb.append(argName);
            }
        }
        return sb.toString();
    }
}
